apiVersion: v1
kind: PersistentVolume
metadata:
  name: historical-db-pv-volume
  labels:
    type: efs
    app: historical-db
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-056e6243c09496444
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: historical-db-pv-claim  # Sets name of PVC
  labels:
    app: historical-db
spec:
  storageClassName: efs-sc
  accessModes:
    - ReadWriteMany  # Sets read and write access
  resources:
    requests:
      storage: 5Gi  # Sets volume size