name: PC Postgres Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  TAG: ${{ github.event.repository.updated_at}}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKERHUB_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_SECRET }}
      run: |
        echo $TAG
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the Docker image
      working-directory: ./pc-postgres/container
      run: |
        docker build . --file Dockerfile --tag jtb75/pc-postgres:$(date +%y.%m.%d.%k) --tag jtb75/pc-postgres:latest
    - name: Push the Docker image
      run: |
        docker push jtb75/pc-postgres
