name: PC Postgres Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKERHUB_USER}}
        DOCKER_PASSWORD: ${{DOCKERHUB_SECRET}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: docker build ./pc-postgres/container --file Dockerfile --tag jtb75/pc-postgres:$(date +%s)
    - name: Push the Docker image
      run: docker push jtb75/pc-postgres:$(date +%s)
