name: PC Postgres Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  TAG: 0.1
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKERHUB_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_SECRET }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the Docker image
      working-directory: ./pc-postgres/container
      run: |
        docker build . --file Dockerfile --tag jtb75/pc-postgres:$TAG --tag jtb75/pc-postgres:latest
    - name: Push the Docker image
      run: |
        docker push jtb75/pc-postgres:$TAG
        docker push jtb75/pc-postgres:latest
